import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar, NavBody, NavItems, NavbarLogo, NavbarButton } from "@/components/ui/resizable-navbar"
import { Inter } from 'next/font/google';
import Footer from "@/components/Footer";

// Initialize the font object
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navItems = [
  { name: "Home", link: "/" },
  { name: "About", link: "/about" },
  { name: "Services", link: "/services" },
  { name: "Contact", link: "/contact" }
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${inter.className} antialiased border-0 border-green-600 flex flex-col min-h-screen`}
      >
        <div className="border-0 border-green-400 pt-[90px]">
          <Navbar>
            <NavBody>
              <NavbarLogo />
              <NavItems items={navItems} />
              <NavbarButton href="/contact" variant="primary">
                Get Started
              </NavbarButton>
            </NavBody>
          </Navbar>
        </div>

        <div className="flex-grow">{children}</div>
        
        {/* <Footer /> */}
        
      </body>
    </html>
  );
}